services:
  - type: web
    name: minecraft-status
    runtime: docker
    repo: https://github.com/stxtxm/event-unlined.git
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://minecraft-status.onrender.com
    healthCheckPath: /
